language: php

sudo: false

php:
    - 7.0
    - 7.1

branches:
  only: master

before_script:
  - composer self-update
  - composer update --prefer-source --prefer-lowest --dev

after_script:
  - vendor/codervio/envmanager/vendor/phpunit/phpunit/phpunit vendor/codervio/envmanager/Tests/ --coverage-clover=coverage.xml


