language: php

sudo: false

php:
    - 7.0
    - 7.1

branches:
  only: master

before_script:
  - composer self-update
  - composer update --prefer-source --prefer-lowest --dev

after_script:
  - ls $TRAVIS_BUILD_DIR
  - ls vendor
  - ls vendor/codervio/envmanager
  - ls vendor/bin/
  - $TRAVIS_BUILD_DIR/vendor/bin/phpunit vendor/codervio/envmanager/Tests/EnvparserTest.php --coverage-clover=coverage.xml


