sudo: false

language: php

php:
    - 7.1
    - 7.2

install:
  - travis_retry composer install --no-interaction --no-suggest
  - composer show --installed

branches:
  only: master

before_script:
  - travis_retry composer self-update

after_script:
  - cd vendor/codervio/envmanager
  - phpunit Tests/ --coverage-clover=coverage.xml


