language: php

sudo: false

php:
    - 7.1

branches:
  only: master

before_script:
  - composer self-update
  - composer update --prefer-source --prefer-lowest --dev

after_script:
  - cd vendor/codervio/envmanager
  - phpunit Tests/ --coverage-clover=coverage.xml


