language: php

sudo: false

env:
  - CODERVIO_PACKAGE="envmanager"

php:
    - 7.0
    - 7.1

branches:
  only: master

before_script:
  - export ENVVARTEST=ENVVALTEST
  - composer self-update
  - composer update --prefer-source --prefer-lowest --dev

after_script:
  - ls $TRAVIS_BUILD_DIR
  - ls $TRAVIS_BUILD_DIR/Tests
  - ls $TRAVIS_BUILD_DIR/vendor/bin/phpunit
  - $TRAVIS_BUILD_DIR/vendor/bin/phpunit $TRAVIS_BUILD_DIR/Tests/EnvparserTest.php --coverage-clover=coverage.xml


