language: php

sudo: false

php:
    - 7.1

branches:
  only: master

before_script:
  - composer install

after_script:
  - ls $TRAVIS_BUILD_DIR
  - ls $TRAVIS_BUILD_DIR/Tests
  - ls $TRAVIS_BUILD_DIR/vendor/bin/phpunit
  - $TRAVIS_BUILD_DIR/vendor/bin/phpunit $TRAVIS_BUILD_DIR/Tests/EnvparserTest.php --coverage-clover=coverage.xml


