language: php

sudo: false

php:
    - 7.0
    - 7.1

branches:
  only: master

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-source
  - composer show --installed

before_script:
  - composer self-update
  - composer update --prefer-source --prefer-lowest --dev

after_script:
  - ls
  - cd /home/travis/build/Codervio/Envmanager
  - phpunit Tests/ --coverage-clover=coverage.xml


