language: php

php:
    - 7.0
    - 7.1
    - 7.2

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev

after_script:
    - cd vendor/codervio/envmanager
    - phpunit Tests/ --coverage-clover=coverage.xml


